import { StyleSheet } from 'react-native';
import { Platform } from 'react-native';
export default StyleSheet.create({
  main: {
    backgroundColor: '#9BBBBE',
    paddingHorizontal: 5,
    minHeight: '100%',
  },
  logo: {
    width: 135,
    height: 117,
    padding: 20,
  },
  logosection: {
    // flex:1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    // marginTop:10
  },

  logo1: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    backgroundColor: '#CED4D8',
    // paddingTop:25,
    overflow: 'hidden',
    // paddingHorizontal:16,
    marginTop: 15,
    borderWidth: 4,
    borderColor: '#CED4D8',
    textAlign: 'center',
    width: 90,
    height: 90,
    borderRadius: 100 / 2,
  },

  label: {
    color: '#000',
    fontSize: 14,
    fontFamily: 'Montserrat-Regular',
  },
  required: {
    color: '#eee',
  },
  signintext: {
    textAlign: 'center',
    fontSize: 30,
    color: '#fff',
    marginTop: 20,
    fontFamily: 'Montserrat-Regular',
  },
  signintextdown: {
    textAlign: 'center',
    fontSize: 30,
    color: '#fff',
    marginBottom: 15,
    fontFamily: 'Montserrat-Bold',
    marginTop: 5,
  },
  required: {
    color: '#E66100',
  },
  forgottext: {
    color: '#BABABA',
    flex: 1,
    textAlign: 'right',
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    marginBottom: 20,
  },
  submitbtn: {
    backgroundColor: '#E66100',
    paddingVertical: 10,
    marginTop: 20,
    borderRadius: 5,
    fontFamily: 'Montserrat-Bold',
  },
  submitbtntext: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Montserrat-Bold',
  },
  loginwith: {
    color: '#fff',
    textAlign: 'center',
    marginVertical: 20,
    fontSize: 18,
    fontFamily: 'Montserrat-Medium',
  },
  socialsection: {
    flex: 2,
    flexDirection: 'row',
  },
  socialmain: {
    marginHorizontal: 10,
  },
  registersection: {
    backgroundColor: '#fff',
    flex: 2,
    flexDirection: 'row',
    marginVertical: 20,
    padding: 20,
    borderRadius: 10,
  },
  regtext1: {
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    color: '#000',
  },
  regtext2: {
    fontSize: 18,
    fontWeight: '700',
    fontFamily: 'Montserrat-Regular',
    color: '#000',
  },
  regbtn: {
    backgroundColor: '#E66100',
    paddingVertical: 10,
    marginTop: 0,
    borderRadius: 5,
    marginLeft: 20,
  },
  regbtntext: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 18,
    width: 100,
    fontWeight: '700',
    fontFamily: 'Montserrat-Medium',
  },
  noaccountmain: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 0,
    marginBottom: 0,
  },
  noaccountmain1: {
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  noaccount: {
    color: '#BABABA',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
  },
  signuptext: {
    color: '#436077',
    fontSize: 16,
    // fontWeight:'700',
    fontFamily: 'Montserrat-Medium',
    textDecorationLine: 'underline',
  },
  eyeicon: {
    position: 'absolute',
    right: 10,
    zIndex: 9999,
    top: 34,
  },
  title: {
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 15,
    color: '#000',
  },
  catbutton: {
    marginRight: 10,
    marginBottom: 10,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,
  },
  catbuttontext: {
    color: '#E66100',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  catbuttonmain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    borderRadius: 50,
  },
  titlemain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  seealltext: {
    color: '#E66100',
    fontFamily: 'Montserrat-Bold',
    marginTop: 3,
  },
  catbuttonorange: {
    marginRight: 10,
    marginBottom: 10,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#E66100',
    paddingRight: 20,
  },
  catbuttontextorange: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  crossicon: {
    position: 'absolute',
    right: 0,
    top: 0,
  },
  bottomsheetmain: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 800,
  },
  bottomsheetheader: {
    backgroundColor: '#eee',
    paddingHorizontal: 10,
    paddingTop: 15,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  orangetitle: {
    color: '#E66100',
  },
  selectmain: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  checkmain: {
    padding: 0,
    margin: 0,
    marginVertical: 10,
  },
  checksection: {
    marginHorizontal: 10,
  },
  checkbtnmain: {
    flexDirection: 'row',
    flex: 2,
    padding: 20,
    marginBottom: 20,
  },
  applybtn: {
    backgroundColor: '#E66100',
    paddingRight: 20,
    flex: 1,
    padding: 10,
  },
  applytext: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  closebtn: {
    flex: 1,
    padding: 10,
  },
  closebtntext: {
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  backorg: {
    position: 'relative',
    top: 3,
  },
  clearall: {
    marginTop: 10,
  },
  space30: {
    height: 30,
  },
  space20: {
    height: 20,
  },
  space10: {
    height: 10,
  },
  cardmain: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 10,
    flex: 2,
    flexDirection: 'row',
    marginBottom: 15,
    paddingBottom: 20,
  },
  cardimg: {
    borderRadius: 7,
  },
  cardinnerright: {
    marginLeft: 10,
    flex: 1,
    paddingTop: 20,
  },
  cardinnerleft: {
    paddingTop: 20,
  },
  cardtext1: {
    color: '#E66100',
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    marginBottom: 5,
  },
  cardtext2: {
    color: '#000',
    fontSize: 18,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 5,
  },
  cardtext3: {
    color: '#000',
    fontSize: 16,
    marginBottom: 5,
    fontFamily: 'Montserrat-Medium',
  },
  pricemain: {
    flexDirection: 'row',
    fontFamily: 'Montserrat-Medium',
    alignItems: 'center',
    marginTop: 5,
  },
  cardtext4: {
    marginRight: 10,
    fontFamily: 'Montserrat-Medium',
    fontSize: 22,
    textDecorationLine: 'line-through',
    color: '#000',
    fontWeight: '600',
  },
  cardtext5: {
    marginRight: 10,
    fontFamily: 'Montserrat-Medium',
    fontSize: 22,
    color: '#059002',
    fontWeight: '600',
  },
  cardtext6: {
    marginRight: 10,
    fontFamily: 'Montserrat-Bold',
    fontSize: 12,
    color: '#fff',
    backgroundColor: '#A9CF4B',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
    overflow: 'hidden',
  },
  cardtext7: {
    marginRight: 10,
    fontFamily: 'Montserrat-Bold',
    fontSize: 12,
    color: '#E66100',
    backgroundColor: 'rgba(254, 90, 62, 0.25)',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },

  image: {
    flex: 1,
    justifyContent: 'flex-end',
    width: 80,
    height: 24,
  },
  text: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'right',
    marginBottom: 9,
    marginRight: 5,
  },
  badgecontainer: {
    width: '100%',
    alignItems: 'flex-end',
    flex: 1,
    position: 'absolute',
    right: -10,
    top: -10,
    fontFamily: 'Montserrat-Medium',
  },
  slidermain: {
    backgroundColor: '#fff',
    flex: 1,
    borderRadius: 10,
  },
  cardmainpopular: {
    // backgroundColor:"#fff",
    padding: 15,
    borderRadius: 10,
    flex: 1,
    flexDirection: 'column',
    marginBottom: 15,
    paddingBottom: 20,
  },
  cardimg1: {
    borderRadius: 7,
    width: '100%',
    height: '60%',
    marginBottom: 20,
    textAlign: 'center',
    alignContent: 'center',
  },
  cardinnerright1: {
    marginLeft: 0,
  },
  space50: {
    height: 50,
  },
  populartitle: {
    marginBottom: -30,
  },
  loadmaintext: {
    textAlign: 'center',
    color: '#fff',
    paddingVertical: 10,
    fontSize: 16,
    paddingHorizontal: 20,
    backgroundColor: '#E66100',
    fontFamily: 'Montserrat-Bold',
    borderRadius: 10,
    position: 'relative',
    overflow: 'hidden',
  },
  loadmain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    borderRadius: 20,
    position: 'relative',
  },
  popcard1: {
    marginTop: 15,
    zIndex: 999999,
  },
  backbtn: {
    color: '#E66100',
    fontFamily: 'Montserrat-Bold',
    fontSize: 20,
    lineHeight: 0,
  },
  banner: {
    width: '100%',
    borderRadius: 50,
    marginVertical: 20,
    minHeight: 100,
    alignContent: 'center',
    justifyContent: 'center',
  },
  mainbanner: {
    marginHorizontal: 10,
    borderRadius: 50,
  },
  bannertext: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 23,
    color: '#fff',
    textAlign: 'center',
    paddingHorizontal: 20,
    textTransform: 'uppercase',
    borderRadius: 50,
  },
  deatilbadgemain: {
    marginHorizontal: 10,
  },
  detailbanner: {
    width: '100%',
    borderRadius: 10,
    marginBottom: 20,
  },
  detailbadgecontainer: {
    top: 8,
    right: 0,
  },
  deatiltitle: {
    color: '#e66100',
    fontFamily: 'Montserrat-Bold',
  },
  detailtitlemain: {
    color: '#000',
    marginTop: 12,
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    flex: 1,
    lineHeight: 25,
  },
  list: {
    flex: 1,
    paddingLeft: 5,
    color: '#000',
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 25,
  },
  list1: {
    color: '#000',
    fontSize: 50,
    fontFamily: 'Montserrat-Medium',
    lineHeight: 39,
  },
  tagmain: {
    flexDirection: 'row',
    marginVertical: 10,
  },
  taginner: {
    backgroundColor: 'rgba(230, 97, 0, 0.05)',
    borderWidth: 1,
    borderColor: '#E66100',
    borderRadius: 15,
    overflow: 'hidden',
    alignContent: 'flex-start',
    justifyContent: 'flex-start',
  },
  tagtext: {
    paddingVertical: 5,
    paddingHorizontal: 30,
    // lineHeight:20,
    position: 'relative',
    overflow: 'hidden',
    paddingRight: 10,
    fontFamily: 'Montserrat-Medium',
  },
  tagimg: {
    position: 'absolute',
    marginHorizontal: 20,
    top: 4,
    bottom: -20,
    left: -10,
  },
  outlinebutton: {
    marginRight: 10,
    marginBottom: 10,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E66100',
  },
  outlinebuttontext: {
    color: '#E66100',
    textAlign: 'center',
    fontFamily: 'Montserrat-Bold',
  },
  outlinebuttonmain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    borderRadius: 50,
    marginVertical: 10,
  },
  outlinebtnicon: {
    marginHorizontal: 20,
    paddingHorizontal: 10,
  },
  deatilsbtnmain: {
    backgroundColor: '#fff',
    margin: 0,
    zIndex: 9999,
    overflow: 'visible',
    height: 70,
    position: 'absolute',
    bottom: -20,
    width: '100%',
  },
  deatilsbtninner: {
    margin: 0,
    padding: 5,
  },
  orgtext: {
    color: '#E66100',
  },
  dashinner: {
    alignContent: 'center',
    alignItems: 'center',
    flex: 1,
  },
  dashmain: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginHorizontal: 10,
    marginVertical: 10,
    paddingVertical: 15,
    flexDirection: 'row',
  },
  dash1: {
    marginBottom: 10,
  },
  dash2: {
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 10,
    textAlign: 'center',
    color: '#000',
  },
  dash3: {
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    color: '#000',
  },
  dashmain2: {
    marginHorizontal: 10,
    marginTop: 10,
  },
  dashdata1: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginVertical: 10,
  },
  dashdata2: {
    // flex:1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  dashdata3: {
    borderRadius: 100,
    width: 50,
    height: 50,
    margin: 10,
  },
  dashdata4: {
    flex: 1,
    margin: 10,
    color: '#000',
  },
  dashdata5: {
    flex: 1,
  },
  dashdata5: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 5,
    color: '#000',
  },
  dashdata6: {
    fontFamily: 'Montserrat-Medium',
    color: '#000',
  },
  dashdata7: {
    fontSize: 15,
    fontFamily: 'Montserrat-Bold',
    color: '#E66100',
    margin: 10,
  },
  selectedbtn: {
    backgroundColor: '#E66100',
    borderRadius: 10,
    borderColor: '#eee',
    borderWidth: 0,
    fontFamily: 'Montserrat-Bold',
    fontSize: 20,
  },
  btncontainer: {
    marginBottom: 20,
    backgroundColor: '#fff',
    borderColor: '#eee',
    borderWidth: 0,
    marginVertical: 20,
    fontSize: 20,
  },
  buttonContainerStyle: {
    backgroundColor: '#f5f5f5',
    borderColor: '#eee',
    borderWidth: 0,
    borderRightWidth: 0,
    fontSize: 20,
  },
  buttonStyle: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 0,
    fontFamily: 'Montserrat-Bold',
    fontSize: 20,
  },
  textStyle: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 16,
    color: '#000',
    fontWeight: '600',
  },
  marginhz15: {
    marginHorizontal: 15,
  },
  expires: {
    right: -25,
    top: -15,
  },
  expirebtn: {
    overflow: 'hidden',
    borderTopRightRadius: 30,
    borderRadius: 10,
  },
  redeemmain: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 40,
    marginHorizontal: 20,
    textAlign: 'center',
  },
  redeemtext1: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    marginTop: 20,
    textAlign: 'center',
    color: '#000',
  },
  redeemtext2: {
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    marginVertical: 10,
    textAlign: 'center',
    marginBottom: 20,
    color: '#000',
  },
  orgoutline: {
    borderWidth: 1,
    borderColor: '#E66100',
    borderRadius: 8,
    padding: 10,
    lineHeight: 20,
  },
  marginright10: {
    marginRight: 10,
  },
  dashdata8: {
    fontSize: 14,
    fontFamily: 'Montserrat-Medium',
    color: '#000',
    margin: 10,
    textAlign: 'center',
  },
  dashdata9: {
    fontFamily: 'Montserrat-Medium',
    color: '#000',
    margin: 10,
    textAlign: 'center',
    backgroundColor: '#E66100',
  },
  chatmain: {
    backgroundColor: '#f5f5f5',
    marginBottom: 0,
    paddingBottom: 0,
  },
  chatinner: {
    borderBottomWidth: 1,
    borderBottomColor: '#c1c1c1',
    paddingBottom: 10,
    marginBottom: 10,
  },
  mainform: {
    backgroundColor: '#fff',
    paddingHorizontal: 30,
    marginVertical: 20,
    marginHorizontal: 20,
    paddingVertical: 20,
    borderRadius: 10,
  },
  orangetitletext: {
    textAlign: 'center',
    fontSize: 18,
    fontFamily: 'Montserrat-Medium',
    color: '#E66100',
  },
  blacktext: {
    color: '#000',
  },
  mainformnobg: {
    paddingHorizontal: 30,
    marginVertical: 20,
    marginHorizontal: 10,
    paddingVertical: 20,
    borderRadius: 10,
  },
  verfimain: {
    margin: 0,
    padding: 0,
    alignItems: 'center',
    alignContent: 'center',
  },
  mainbg: {
    marginHorizontal: 20,
    marginVertical: 20,
  },
  date: {
    paddingBottom: 10,
  },
  notimain: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 10,
    fontFamily: 'Montserrat-Medium',
    borderLeftWidth: 3,
    borderLeftColor: '#E66100',
    marginBottom: 20,
  },
  noti1: {
    paddingBottom: 10,
    fontSize: 20,
    fontFamily: 'Montserrat-Medium',
  },
  noti2: {
    paddingBottom: 10,
    fontSize: 16,
    fontFamily: 'Montserrat-Medium',
  },
  sellertextbold: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 15,
  },
  sellertext: {
    fontFamily: 'Montserrat-Medium',
    marginBottom: 10,
    fontSize: 15,
  },
  dropdown1: {
    borderRadius: 5,
    paddingHorizontal: 5,
    borderColor: '#000',
    borderWidth: 1,
    marginVertical: 10,
    paddingVertical: 3,
  },
  placeholderStyle1: {
    fontSize: 16,
  },
  selectedTextStyle1: {
    fontSize: 16,
    marginLeft: 8,
  },
  textarea: {
    height: 100,
  },
  checkoutmain: {
    marginHorizontal: 20,
    marginVertical: 20,
  },
  checktext1: {
    fontSize: 16,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 8,
  },
  checktext2: {
    fontSize: 15,
    fontFamily: 'Montserrat-Medium',
    marginBottom: 8,
  },
  orangetitlebold: {
    fontSize: 18,
    fontFamily: 'Montserrat-Bold',
    marginBottom: 8,
    color: '#E66100',
    marginTop: 20,
    marginBottom: 10,
  },
  innerradiocheckout: {
    marginLeft: 20,
  },
  headerhome: {
    // height: 110,
    // paddingTop:50,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    ...Platform.select({
      ios: {
        paddingTop: 50,
        height: 120,
      },
      android: {
        paddingTop: 10,
        height: 80,
      },
    }),
  },
  headerhomeadr: {
    height: 80,
    paddingTop: 10,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerhomeios: {
    height: 110,
    paddingTop: 50,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerright: {
    flexDirection: 'row',
    marginTop: 10,
  },
  serachmain: {
    flexDirection: 'row',
  },
  notify: {
    marginRight: 25,
    marginTop: 6,
  },
  profile: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 23,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#ccc',
  },
  receive: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 17,
    marginBottom: 30,
    marginTop: 10,
  },
  radio: {
    backgroundColor: '#000',
    color: '#fff',
    opacity: 1,
  },
  space: {
    height: 20,
  },
  otp: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
  },
  otpmain: {
    marginBottom: 40,
    fontFamily: 'Montserrat-Medium',
  },

  createaccsec: {
    backgroundColor: '#fff',
    flex: 1,
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  welcomesec: {
    flex: 1,
    flexDirection: 'column',
  },
  containers: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#9BBBBE',
  },
  welcome1: {
    flex: 0.5,
    backgroundColor: '#9BBBBE',

    ...Platform.select({
      ios: {
        paddingTop: 50,
      },
      android: {
        paddingTop: 0,
      },
    }),
  },
  welcome2: {
    flex: 1,
    backgroundColor: '#fff',
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
    shadowOffset: { width: 5, height: 9 },
    shadowColor: '#171717',
    shadowOpacity: 0.9,
    shadowRadius: 10,
    textAlign: 'center',
    alignItems: 'center',
    paddingTop: 30,
    paddingHorizontal: 20,
  },
  weltext1: {
    color: '#BABABA',
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
    paddingBottom: 30,
  },
  graybtn: {
    backgroundColor: '#DADDDD',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 25,
    borderRadius: 10,
    marginBottom: 20,
  },
  graybtntext: {
    fontSize: 20,
    fontFamily: 'Montserrat-Regular',
    color: '#436077',
  },
  bluebtn: {
    backgroundColor: '#436077',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 25,
    borderRadius: 10,
    marginBottom: 20,
  },
  bluebtntext: {
    fontSize: 20,
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
  },
  bluebtnsmall: {
    backgroundColor: '#436077',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 15,
    borderRadius: 10,
    marginBottom: 20,
    // margin:10
  },
  savebtn: {
    padding: 20,
  },
  savebtn1: {
    padding: 10,
    width: 180,
  },
  bluebtnsmallact: {
    backgroundColor: '#436077',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    marginBottom: 5,
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  bluebtnsmallSave: {
    backgroundColor: '#436077',
    width: '30%',
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    marginBottom: 5,
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  bluebtnsmallImg: {
    backgroundColor: '#436077',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    marginBottom: 10,
    padding: 10,
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  bluebtnsmalltextImg: {
    fontSize: 17,
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
    padding: 5,
  },
  bluebtnsmalltextSave: {
    fontSize: 17,
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
  },
  bluebtnsmalltexttracker: {
    fontSize: 17,
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
    margin: 6,
  },
  bluebtnsmallTrack: {
    backgroundColor: '#436077',
    width: '100%',
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    margin: 5,
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  bluebtnsmalltextDiscover: {
    fontSize: 17,
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
  },
  bluebtnsmallDiscover: {
    backgroundColor: '#436077',
    width: '45%',
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    marginBottom: 5,
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  bluebtnsmalltext: {
    fontSize: 18,
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
    textAlign: 'center',
  },
  bluebtnsmallEdit: {
    backgroundColor: '#436077',
    width: '25%',
    alignItems: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    marginBottom: 0,
    textAlign: 'center',
  },
  bluebtnsmalltextEdit: {
    fontSize: 15,
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
  },
  termtext: {
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Montserrat-Medium',
  },
  createacc: {
    fontSize: 30,
    // lineHeight:20,
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    color: '#436077',
    paddingTop: 0,
  },
  createacc2: {
    fontSize: 22,
    // lineHeight:20,
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    color: '#436077',
  },
  fleamain: {
    margin: 20,
    marginTop: 40,
  },
  labelContainer: {
    alignSelf: 'flex-start', // Have View be same width as Text inside
    paddingHorizontal: 3, // Amount of spacing between border and first/last letter
    marginStart: 10, // How far right do you want the label to start
    zIndex: 1, // Label must overlap border
    elevation: 1, // Needed for android
    shadowColor: 'white', // Same as background color because elevation: 1 creates a shadow that we don't want
    position: 'absolute', // Needed to be able to precisely overlap label with border
    top: 15, // Vertical position of label. Eyeball it to see where label intersects border.
  },
  inputContainer: {
    borderWidth: 1, // Create border
    borderRadius: 8, // Not needed. Just make it look nicer.
    zIndex: 0, // Ensure border has z-index of 0
    paddingLeft: 9,
    // paddingTop:30,
    ...Platform.select({
      ios: {
        paddingTop: 40,
        paddingBottom: 10,
      },
      android: {
        paddingTop: 30,
        paddingBottom: 3,
      },
    }),
    // paddingBottom:3,
    color: '#436077',
    borderColor: '#CDD4D9',
  },
  inputContainerDrop: {
    borderWidth: 1, // Create border
    borderRadius: 8, // Not needed. Just make it look nicer.
    zIndex: 0, // Ensure border has z-index of 0
    paddingLeft: 9,
    // paddingTop:30,
    ...Platform.select({
      ios: {
        paddingTop: 30,
        paddingBottom: 1,
      },
      android: {
        paddingTop: 30,
        paddingBottom: 2,
      },
    }),
    // paddingBottom:3,
    color: '#436077',
    borderColor: '#CDD4D9',
  },
  input: {
    color: '#436077',
    borderRadius: 5,
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
    color: '#436077',
  },
  inputmain: {
    marginBottom: 20,
    width: '100%',
  },

  passwordmain: {
    // flex:2,
    // flexDirection:'row',
    // justifyContent:"space-between",
    // width:"100%"
    paddingRight: 60,
  },
  password: {
    marginRight: 10,
    position: 'absolute',
    right: 10,
    top: 27,
    cursor: 'pointer',
  },
  ortext: {
    textAlign: 'center',
    marginBottom: 20,
    fontSize: 20,
    color: '#BABABA',
    fontFamily: 'Montserrat-Medium',
  },
  forgotcontent: {
    fontSize: 15,
    color: '#BABABA',
    fontFamily: 'Montserrat-Medium',
    paddingTop: 15,
    textAlign: 'center',
    marginVertical: 20,
  },
  shortText: {
    fontSize: 15,
    color: '#BABABA',
    fontFamily: 'Montserrat-Medium',
    paddingTop: 5,
    textAlign: 'center',
    marginVertical: 15,
  },
  dot: {
    backgroundColor: '#DBDDDD',
    margin: 10,
    width: 15,
    height: 15,
    borderRadius: 50,
  },
  dotmain: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  dotactive: {
    backgroundColor: '#495F75',
    margin: 8,
    width: 15,
    height: 15,
    borderRadius: 50,
  },
  onboardtext: {
    color: '#495F75',
    fontFamily: 'Montserrat-Regular',
    fontSize: 20,
    textAlign: 'center',
    marginTop: 20,
  },
  arrowright: {
    textAlign: 'right',
    alignItems: 'flex-end',
    marginTop: 35,
    marginRight: 10,
  },
  navheader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  skiptext: {
    color: '#223656',
    fontFamily: 'Montserrat-Medium',
    fontSize: 18,
    marginTop: 10,
  },
  elementinput: {
    borderBottomWidth: 0,
    borderColor: '#fff',
    Width: 100,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    alignContent: 'center',
  },
  editnamemain: {
    flexDirection: 'row',
    justifyContent: 'center',
    // marginTop:20,
    marginBottom: 5,
  },
  editnametext: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    marginTop: 3,
    // marginHorizontal: 10,
  },
  familytext: {
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    textAlign: 'center',
    opacity: 0.4,
    marginTop: -5,
  },
  selecttext: {
    paddingLeft: 60,
    marginBottom: 0,
  },
  leftselect: {
    position: 'absolute',
    bottom: 10,
    width: 25,
  },
  placeholderStyle: {
    marginHorizontal: 20,
    paddingLeft: 40,
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    opacity: 0.4,
  },
  selectedTextStyle: {
    marginHorizontal: 20,
    paddingLeft: 40,
    color: '#000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    opacity: 1,
    ...Platform.select({
      ios: {},
      android: {
        paddingTop: 8,
        paddingBottom: 10,
      },
    }),
  },
  dropdown: {
    marginRight: 20,
    height: 35,
  },
  activitylabel: {
    color: '#000000', // Set the text color here
  },
  selecticon: {
    marginLeft: 10,
  },
  // profilesec:{
  //   flex:1,
  //   flexDirection:"column",
  //   justifyContent:"center",
  //   alignItems:"center"
  // },
  forgotcontent1: {
    fontSize: 15,
    color: '#BABABA',
    fontFamily: 'Montserrat-Medium',
    paddingTop: 15,
    textAlign: 'center',
    marginVertical: 20,
    lineHeight: 30,
  },
  inputContainer1: {
    borderWidth: 1, // Create border
    borderRadius: 8, // Not needed. Just make it look nicer.
    zIndex: 0, // Ensure border has z-index of 0
    paddingLeft: 9,
    // paddingTop:30,
    ...Platform.select({
      ios: {
        paddingTop: 10,
        paddingBottom: 10,
      },
      android: {
        paddingTop: 0,
        paddingBottom: 3,
      },
    }),
    // paddingBottom:3,
    color: '#436077',
    borderColor: '#CDD4D9',
  },
  selectedTextStyle2: {
    fontSize: 16,
    marginLeft: 8,
    paddingVertical: 5,
    color: '#495F75',
    fontFamily: 'Montserrat',
  },
  selectedTextStyleAct: {
    fontSize: 16,
    paddingVertical: 5,
    color: '#495F75',
    fontFamily: 'Montserrat-Bold',
    width: '100%',
  },
  finish: {
    marginHorizontal: 40,
    marginVertical: 40,
  },
  dogimg: {
    width: 300,
    height: 300,
  },
  dogimg1: {
    width: 200,
    height: 200,
    margin: 10,
  },

  addicon: {
    position: 'absolute',
    bottom: 3,
  },
  Choose_Subs: {
    textAlign: 'center',
    fontFamily: 'Montserrat-bold',
    marginTop: 10,
    color: '#495F75',
    fontSize: 33,
  },
  cards_Year: {
    flex: 1,
    color: 'black',
    marginTop: 80,
  },
  tabmain_subs: {
    flex: 1,
    backgroundColor: '#fff',
    ...Platform.select({
      ios: {
        paddingTop: 0,
        paddingBottom: 5,
      },
      android: {
        paddingTop: 20,
        paddingBottom: 3,
      },
    }),
  },
  tabmain: {
    flex: 1,
    backgroundColor: '#fff',
    ...Platform.select({
      ios: {
        paddingTop: 50,
        paddingBottom: 5,
      },
      android: {
        paddingTop: 20,
        paddingBottom: 3,
      },
    }),
  },
  topheader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 10,
  },
  chattopheader: {
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    marginTop: 600,
    marginLeft: 300,
    marginHorizontal: 20,
    marginTop: 10,
  },
  editnameorg: {
    color: '#CE5757',
    fontFamily: 'Montserrat-Bold',
    marginTop: 40,
  },
  todaysec: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: 10,
  },
  todaytext: {
    color: '#436077',
    fontFamily: 'Montserrat-Bold',
    fontSize: 25,
  },
  homecardmain: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    margin: 12,
  },
  homecardinner: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.41,
    elevation: 23,
    flex: 1,
    margin: 15,
    borderRadius: 10,
    alignItems: 'center',
    padding: 20,
  },
  homecardtext: {
    color: '#436077',
    fontFamily: 'Montserrat-Bold',
    fontSize: 15,
  },
  homecardtextSmall: {
    color: '#436077',
    fontFamily: 'Montserrat-Bold',
    fontSize: 12,
  },
  homecardvalue: {
    color: '#9BBBBE',
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
    backgroundColor: '#9BBBBE4D',
    paddingVertical: 30,
    // borderRadius:40,
    overflow: 'hidden',
    paddingHorizontal: 30,
    marginTop: 5,
    borderWidth: 4,
    borderColor: '#9BBBBE',
    textAlign: 'center',
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    justifyContent: 'center',
    alignContent: 'center',
    marginBottom: 25,
    fontWeight: '600',
  },
  homecardvalue1: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
    backgroundColor: '#CED4D8',
    paddingTop: 25,
    overflow: 'hidden',
    paddingHorizontal: 16,
    marginTop: 15,
    borderWidth: 4,
    borderColor: '#495F75',
    textAlign: 'center',
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
  },
  activitymain: {
    flexDirection: 'row',
    marginTop: 10,
  },
  activityfill: {
    backgroundColor: '#9BBBBE',
    width: 30,
    height: 30,
    borderRadius: 5,
    overflow: 'hidden',
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: '#9BBBBE',
  },
  activityfillSmall: {
    backgroundColor: '#9BBBBE',
    width: 20,
    height: 20,
    borderRadius: 3,
    overflow: 'hidden',
    marginHorizontal: 3.5,
    borderWidth: 1,
    borderColor: '#9BBBBE',
  },
  activityunfill: {
    backgroundColor: '#fff',
    width: 30,
    height: 30,
    borderRadius: 5,
    overflow: 'hidden',
    marginHorizontal: 5,
    borderWidth: 1,
    borderColor: '#495F75',
  },
  activityunfillSmall: {
    backgroundColor: '#fff',
    width: 20,
    height: 20,
    borderRadius: 5,
    overflow: 'hidden',
    marginHorizontal: 3,
    borderWidth: 1,
    borderColor: '#495F75',
  },

  actmain: {
    marginTop: 15,
  },
  energy: {
    marginTop: 10,
  },
  caltext: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
  },
  bluebtnsmallmain: {
    marginHorizontal: 30,
    marginVertical: 20,
  },
  scrollmain: {
    flex: 1,
    flexDirection: 'column',
  },
  // profilemain: {
  //   flex: 1,
  // },

  profilename: {
    textAlign: 'center',
    // color: '#CE5757',
    color: '#CE5757',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    marginBottom: 10,
  },
  maintitle: {
    color: '#495F75',
    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
    textAlign: 'center',
    marginVertical: 20,
  },
  homecardinner1: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.41,
    elevation: 23,
    flex: 1,
    margin: 15,
    borderRadius: 10,
    padding: 20,
  },

  homecardtext1: {
    color: '#436077',
    fontFamily: 'Montserrat-Bold',
    fontSize: 16,
  },
  activityComment: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
  },
  healthcircle: {
    alignItems: 'center',
    marginTop: 20,
  },
  healthcircleinner: {
    borderWidth: 4,
    borderColor: '#9BBBBE',
    overflow: 'hidden',
    width: 150,
    height: 150,
    borderRadius: 150 / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  homecardvalue2: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 18,
    backgroundColor: '#fff',
    paddingTop: 50,
    // borderRadius:40,
    overflow: 'hidden',
    paddingHorizontal: 30,
    borderWidth: 4,
    borderColor: '#495F75',
    textAlign: 'center',
    width: 140,
    height: 140,
    borderRadius: 140 / 2,
    justifyContent: 'center',
    alignContent: 'center',
    margin: 1,
  },
  act1: {
    flexDirection: 'row',
    marginTop: 20,
  },
  act2: {
    marginLeft: 20,
    marginTop: 15,
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
  },
  act5: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 13,
    paddingLeft: 5,
    overflow: 'hidden',
  },
  act4: {
    marginHorizontal: 10,
    alignItems: 'center',
    overflow: 'hidden',
  },
  tabmain1: {
    flex: 0.25,
    height: 20,
    flexDirection: 'column',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
  tabmain2: {
    flex: 1,
    backgroundColor: '#fff',
  },
  homecardvalue3: {
    textAlign: 'center',
    justifyContent: 'center',
    flex: 1,
    // margin:0,
    // padding:0,
    // marginLeft:10
  },
  homecardvalue4: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 18,
    backgroundColor: '#9BBBBE',
    paddingTop: 10,
    // borderRadius:40,
    overflow: 'hidden',
    paddingHorizontal: 6,
    borderWidth: 4,
    borderColor: '#495F75',
    textAlign: 'center',
    width: 120,
    height: 120,
    borderRadius: 120 / 2,
    justifyContent: 'center',
    alignContent: 'center',
    margin: 1,
  },
  caltext1: {
    color: '#495F75',
    fontFamily: 'Montserrat-Bold',
    fontSize: 15,
    marginTop: 20,
  },
  piccenter: {
    textAlign: 'center',
    alignContent: 'center',
    alignItems: 'center',
    position: 'relative',
    bottom: 50,
  },
  energyspace: {
    paddingTop: 30,
    paddingBottom: 50,
    paddingHorizontal: 30,
  },
  food1: {
    marginTop: 20,
    textAlign: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  foodvalue: {
    textAlign: 'right',
    color: '#CE5757',
    fontFamily: 'Montserrat-Medium',
    fontSize: 15,
  },
  foodcardinner: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.41,
    elevation: 23,
    flex: 1,
    margin: 15,
    borderRadius: 10,
    padding: 20,
  },
  foodcardtext: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 15,
  },
  foodimg: {
    width: 100,
    height: 100,
  },
  marhoz15: {
    marginHorizontal: 15,
  },
  padhoz15: {
    paddingHorizontal: 15,
  },
  tabmain3: {
    flex: 1,
    backgroundColor: '#CED4D8',
    borderRadius: 20,
    overflow: 'hidden',
    // marginHorizontal:20,
    marginRight: 20,
    marginLeft: 20,
  },
  mainpage: {
    flex: 1,
    backgroundColor: '#fff',
  },
  chart: {
    alignContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    padding: 15,
  },
  charttitle: {
    color: '#979797',
    fontFamily: 'Montserrat-Bold',
    fontSize: 25,
    marginTop: 20,
    marginBottom: 10,
  },
  gradientBackground: {
    flex: 1,
    padding: 10,
    borderRadius: 10,
    margin: 10,
  },
  chartsubtitle: {
    color: '#979797',
    fontFamily: 'Montserrat-Regular',
    fontSize: 20,
  },
  chartlabel: {
    color: '#979797',
    fontFamily: 'Montserrat-Regular',
    fontSize: 20,
  },
  chartlabel1: {
    color: '#979797',
    fontFamily: 'Montserrat-Regular',
    fontSize: 2,
  },
  homecardinner2: {
    alignItems: 'center',
    flexDirection: 'column',
  },
  act3: {
    flexDirection: 'column',
    alignItems: 'center',
  },
  bluebtnsmallmain1: {
    marginHorizontal: 0,
    marginVertical: 20,
  },
  imgcenter: {
    alignItems: 'center',
  },
  createacc1: {
    textAlign: 'left',
    marginBottom: 0,
  },
  forgotcontent2: {
    fontSize: 15,
    color: '#BABABA',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'left',
    marginVertical: 0,
    lineHeight: 30,
  },
  logmain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logdate: {
    fontSize: 13,
    color: '#949494',
    fontFamily: 'Montserrat-Medium',
    paddingTop: 3,
  },
  brownbtn: {
    backgroundColor: '#CE5757',
    width: 'auto',
    overflow: 'hidden',
    paddingVertical: 5,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginRight: 10,
    marginTop: 10,
  },
  brownbtnActivities: {
    backgroundColor: '#CE5757',
    width: 110,
    overflow: 'hidden',
    paddingVertical: 5,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginRight: 10,
    marginTop: 10,
  },
  brownbtnLog: {
    textAlign: 'center',
    backgroundColor: '#436077',
    width: 120,
    overflow: 'hidden',
    paddingVertical: 5,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginRight: 10,
    marginTop: 10,
  },
  brownbtntext: {
    fontSize: 13,
    color: '#fff',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
  },
  brownbtnmain: {
    flexDirection: 'row',
  },
  logpic: {
    borderRadius: 10,
    marginRight: 10,
  },
  aligncenter: {
    alignItems: 'center',
  },
  brownbtnaligncenter: {
    alignItems: 'center',
    flexDirection: 'column',
    margin: 0,
    marginRight: 0,
  },
  brownbtngraybtn: {
    backgroundColor: '#495F754D',
  },
  space10: {
    height: 10,
  },
  space7: {
    height: 7,
  },
  newsfeedhead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    overflow: 'hidden',
    marginHorizontal: 15,
    marginVertical: 20,
    alignItems: 'center',
  },
  newsfeedhead1: {
    marginVertical: 0,
    marginTop: 5,
  },
  newsfeedhead2: {
    marginRight: 0,
    backgroundColor: '#495F75',
  },

  logmain1: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  logmain2: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 30,
  },
  newsimg: {
    width: 80,
    height: 80,
    borderRadius: 50,
    marginRight: 10,
  },
  newsimg1: {
    width: 55,
    height: 55,
    borderRadius: 50,
    marginRight: 10,
  },
  blue: {
    color: '#436077',
  },
  likesec: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
  },
  likesec1: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 0,
    marginBottom: 30,
    gap: 5,

  },
  homecardinner3: {
    marginHorizontal: 15,
    overflow: 'scroll',
    // height: 50,
    flex: 1,
  },
  feedsec: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 30,
    alignItems: 'center',
    alignContent: 'center',
    marginTop: 20,
  },
  feedtext: {
    fontSize: 12,
    color: '#949494',
    fontFamily: 'Montserrat-Medium',
    marginTop: 10,
  },
  feedsec1: {
    alignItems: 'center',
  },
  feedsec2: {
    alignItems: 'right',
  },
  feedsec: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 30,
    alignItems: 'center',
    alignContent: 'center',
    marginTop: 20,
  },

  feedsecWho: {
    margin: 10,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  menutitle: {
    fontSize: 16,
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    padding: 0,
    margin: 0,
  },
  menumain: {
    marginTop: 20,
  },
  closebtnmenu: {
    textAlign: 'right',
    alignItems: 'flex-end',
    marginRight: 10,
    marginTop: 10,
  },
  errormsg: {
    color: '#B85A57',
    paddingLeft: 5,
    paddingTop: 5,
    fontFamily: 'Montserrat-Regular',
    fontSize: 13,
  },
  prodemain: {
    flexDirection: 'row',
    gap: 2,
    marginTop: 1,
  },
  bluebtnsmallmain2: {
    // marginHorizontal:10,
    // marginVertical:20,
    width: '100%',
    padding: 20,
    alignItems: 'center',
  },
  bluebtnverysmall: {
    backgroundColor: '#436077',
    width: '80%',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
  },
  bluebtnverysmalltext: {
    fontSize: 15,
    fontFamily: 'Montserrat-Bold',
    color: '#fff',
  },
  activestatetext: {
    fontSize: 13,
    fontFamily: 'Montserrat-Medium',
    color: '#BABABA',
    marginLeft: 22,
  },
  activestatemain: {
    marginLeft: 20,
    marginTop: 5,
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
  },
  imeilabel: {
    color: '#436077',
    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
    // margin:5
  },
  imeitext: {
    color: '#BABABA',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    paddingTop: 8,
    // marginLeft:30
  },
  addprofilemain: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  addprofileinner: {
    flex: 1,
    marginTop: 20,
  },
  addprofiletext: {
    textAlign: 'center',
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    paddingBottom: 10,
  },
  addprofilemain1: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  addprofileinner1: {
    marginTop: 10,
  },
  addprofiletext1: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
    marginLeft: 10,
  },
  addprofiletext12: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
    marginLeft: 20,
    textAlign: 'center',
    margin: 50,
  },
  addprofiletext2: {
    color: '#BABABA',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    marginLeft: 10,
  },
  myfamilytext: {
    fontSize: 25,
    // lineHeight:20,
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    color: '#436077',
    paddingTop: 20,
    paddingBottom: 10,
  },
  exittext: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
  },
  unitmain: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  unitinner2: {
    flex: 0.5,
    marginLeft: 10,
  },
  unitinner1: {
    flex: 1,
  },
  inputunitContainer3: {
    borderWidth: 1, // Create border
    borderRadius: 8, // Not needed. Just make it look nicer.
    zIndex: 0, // Ensure border has z-index of 0
    paddingLeft: 0,
    // paddingTop:30,
    ...Platform.select({
      ios: {
        paddingTop: 10,
        paddingBottom: 5,
      },
      android: {
        paddingTop: 0,
        paddingBottom: 3,
      },
    }),
    // paddingBottom:3,
    color: '#436077',
    borderColor: '#CDD4D9',
  },
  placeholderStyleunit: {
    marginHorizontal: 20,
    //paddingLeft:40,
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    opacity: 0.6,
  },
  placeholderStyleEditunit: {
    marginHorizontal: 20,
    //paddingLeft:40,
    color: '#000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    opacity: 0.4,
  },
  selectedTextStyleunit: {
    fontSize: 16,
    marginLeft: 8,
  },
  ProfileLogoCompare: {
    width: 62,
    height: 62,
    borderRadius: 50,
    marginBottom: 10,
  },
  ProfileLogoDiv: {
    width: 30,
  },
  ProfileLogo: {
    width: 80,
    height: 80,
    borderRadius: 50,
    marginBottom: 10,
  },
  likesImage: {
    width: 25,
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  ProfileLogoDes: {
    width: 50,
    height: 50,
    borderRadius: 50,
    borderWidth: 5,
    borderColor: '#fff',
  },
  ProfileLogoBig: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  uploadphotomain: {
    flexDirection: 'row',
    gap: 2,
  },
  uploadphotoinner: {
    flex: 1,
    alignItems: 'center',
  },
  uploadtext: {
    color: '#000000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    marginLeft: 11,
    marginTop: 10,
  },
  bottomsheetmainsmall: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 300,
  },
  bottomsheetmainMedium: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 500,
  },
  bottomsheetmainMediumbtn: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 550,
  },
  bottomsheetImages: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 200,
  },
  bottomsheetmainsmallDuration: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 320,
  },
  bottomsheetmainAddfriend: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 600,
  },
  adduploadmain: {
    position: 'relative',
    flex: 1,
    alignItems: 'center',
    overflow: 'hidden',
  },
  addupload: {
    borderRadius: 50,
    overflow: 'hidden',
  },
  addupload1: {},
  editright: {
    flex: 1,
    alignItems: 'center',
  },
  editsameline: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    alignItems: 'center',
  },
  editinner: {
    justifyContent: 'flex-end',
    //  alignContent: 'flex-end',
    textAlign: 'right',
    verticalAlign: 'middle',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
  },
  bogedittext: {
    fontWeight: 'bold',
  },
  toyboxmain: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginTop: 10,
    alignContent: 'flex-start',
    textAlign: 'left',
  },
  mb6: {
    marginBottom: 6,
  },
  nodatatext: {
    flex: 1,
    textAlign: 'center',
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 17,
    marginTop: 40,
  },
  requiredErr: {
    color: '#B85A57',
    fontFamily: 'Montserrat-Regular',
    fontSize: 13,
    textAlign: 'center',
  },
  iemEdit: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  unitmain1: {
    flexDirection: 'row',
  },

  unitinner4: {
    flex: 1,
    marginLeft: 10,
    paddingTop: 20,
  },
  unitinner3: {
    flex: 0.6,
  },
  addmanuallytext: {
    color: '#436077',
    fontFamily: 'Montserrat-Regular',
    fontSize: 15,
    paddingBottom: 8,
  },
  unitinner5: {
    flex: 1,
    marginLeft: 10,
    paddingTop: 20,
  },
  unitinner6: {
    flex: 1,
    marginLeft: 10,
    paddingTop: 20,
  },
  marginhz20: {
    marginHorizontal: 20,
  },
  dflex: {
    flexDirection: 'row',
    flex: 2,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  dflexMet: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    gap: 10,
  },
  dflex2: {
    flexDirection: 'row',
    flex: 2,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },

  flex1: {
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  compareprofilepic: {
    width: 40,
    height: 40,
    borderRadius: 50,
  },
  comparetext: {
    color: '#436077',
    fontFamily: 'Montserrat-Regular',
    textAlign: 'center',
    fontSize: 16,
    width: '100%',
  },
  comparetextRight: {
    color: '#436077',
    fontFamily: 'Montserrat-Regular',
    textAlign: 'center',
    fontSize: 16,
    width: '100%',
  },
  flex11: {
    flex: 1,
  },
  dflex11: {
    flexDirection: 'row',
    flex: 2,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
  },
  comparetext1: {
    color: '#436077',
    fontFamily: 'Montserrat-Regular',
    textAlign: 'left',
    paddingTop: 10,
    alignItems: 'center',
  },

  // priya-personality
  // personality
  personalityImg: {
    width: 238,
    height: 180,
    // marginTop:-18,
    borderRadius: 15,
  },
  personalityText: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 25,
    fontWeight: '800',
    textAlign: 'center',
  },
  // toys
  tabmain4: {
    flex: 1,
    backgroundColor: '#CED4D8',
    borderRadius: 0,
    overflow: 'hidden',
    // marginHorizontal:20,
    marginTop: 15,
    borderRadius: 50,
  },
  tabSec: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  activeTab: {
    color: '#fff',
    backgroundColor: '#495F75',
    padding: 10,
    borderRadius: 50,
  },
  InactiveTab: {
    color: '#495F75',
    backgroundColor: '#CED4D8',
    padding: 10,
  },
  mayBeactiveTab: {
    color: '#fff',
    backgroundColor: '#495F75',
    padding: 10,
    borderRadius: 50,
    width: 80,
  },
  mayBeInactiveTab: {
    color: '#495F75',
    backgroundColor: '#CED4D8',
    padding: 10,
  },
  selectswitch: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    padding: 3,
  },
  switchtext: {
    fontSize: 15,
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    paddingTop: 10,
    width: 120,
  },

  // food
  addFood: {
    fontSize: 20,
    // lineHeight:20,
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    color: '#436077',
    paddingTop: 0,
    textAlign: 'center',
  },

  // profile
  profileList: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },

  // edit-toys-list
  toysMain: {
    marginHorizontal: 40,
    width: 280,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  toysitem: {
    flex: 1,
    minWidth: 100,
    maxWidth: 100,
    height: 30,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    textAlign: 'left',
    padding: 3,
    // backgroundColor: "rgba(249, 180, 45, 0.25)",
    borderWidth: 1.5,
    borderColor: '#fff',
  },
  centerHeading: {
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  //grid-comapre
  itemGrid: {
    flex: 1,
    height: 160,
    margin: 1,
  },
  listGrid: {
    flex: 1,
    alignItems: 'center',
  },
  activitiesView: {
    marginBottom: 30,
  },

  // datePicker
  dateTimePicker: {
    textAlign: 'left',
    alignItems: 'center',
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 15,
    color: '#436077',
  },
  inputSearchStyle1: {
    textAlign: 'left',
    alignItems: 'center',
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 15,
    color: '#436077',
  },
  timerHead: {
    textAlign: 'center',
    display: 'flex',
    justifyContent: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontSize: 18,
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    color: '#436077',
  },
  timer: {
    textAlign: 'center',
    display: 'flex',
    justifyContent: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  inputunitContainer4: {
    borderWidth: 1, // Create border
    borderRadius: 8, // Not needed. Just make it look nicer.
    color: '#436077',
    borderColor: '#CDD4D9',
    width: 110,
  },
  selectedTextStylePlace: {
    fontSize: 14,
    marginLeft: 8,
    paddingVertical: 5,
    color: '#495F75',
    fontFamily: 'Montserrat-Bold',
    width: '100%',
  },
  activityImg: {
    width: 55,
    height: 55,
    margin: 10,
  },
  listGridActivities: {
    alignItems: 'center',
    marginLeft: 7,
  },
  homecardinnerAct: {
    flex: 1,
    margin: 1,
    borderRadius: 10,
    padding: 1,
  },
  moreText: {
    fontSize: 25,
    color: '#000',
  },
  // kavitha-completed Activity
  distancetext: {
    fontSize: 20,
    marginLeft: 8,
    paddingVertical: 5,
    color: '#495F75',
    fontFamily: 'Montserrat-Bold',
    marginTop: 50,
  },
  healthcircle1: {
    alignItems: 'center',
    marginTop: 20,
  },
  healthcircleinner1: {
    borderWidth: 4,
    borderColor: '#9BBBBE',
    overflow: 'hidden',
    width: 130,
    height: 130,
    borderRadius: 130 / 2,
  },
  homecardvalue3: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 18,
    backgroundColor: '#fff',
    paddingTop: 30,
    // borderRadius:40,
    overflow: 'hidden',
    paddingHorizontal: 30,
    borderWidth: 4,
    borderColor: '#495F75',
    textAlign: 'center',
    width: 120,
    height: 120,
    borderRadius: 120 / 2,
    justifyContent: 'center',
    alignContent: 'center',
    margin: 1,
  },
  place: {
    margin: 5,
  },
  placeimg: {
    width: 110,
    height: 110,
    borderRadius: 10,
  },
  placeimgMt: {
    width: 110,
    height: 110,
    borderWidth: 2,
    borderColor: '#495F75',
    borderStyle: 'dotted',
    borderRadius: 10,
  },
  addplace: {
    position: 'absolute',
    right: 0,
    zIndex: 1,
  },
  metmain: {
    margin: 2,
  },
  metmainpic: {
    width: 40,
    height: 40,
    borderRadius: 50,
  },
  metProfile: {
    gap: 4,
    alignItems: 'flex-start',
  },
  metsec: {
    // backgroundColor: '#495F75',
    marginHorizontal: 10,
    marginVertical: 10,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 20,
    paddingRight: 10,
  },
  mettext: {
    fontSize: 18,
    marginLeft: 8,
    marginRight: 8,
    color: '#000',
    fontFamily: 'Montserrat-medium',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(52, 52, 52, 0.8)',
  },
  modalView: {
    margin: 20,
    backgroundColor: '#CED4D8',
    borderRadius: 20,
    padding: 35,

    shadowColor: 'rgba(22, 67, 217, 0.33)',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.67,
    shadowRadius: 4,
    elevation: 5,
    paddingTop: 0,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    alignItems: 'flex-end',
    top: -40,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 5,
    textAlign: 'center',
    color: '#495F75',
    fontFamily: 'Montserrat-Bold',
    fontSize: 22,
    marginTop: -25,
  },
  logopopup: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    position: 'relative',
    top: -40,
    textAlign: 'center',
  },

  homecardinnerSmall: {
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.41,
    elevation: 23,
    flex: 1,
    margin: 15,
    borderRadius: 10,
    alignItems: 'center',
    padding: 10,
  },
  cardList: {
    textAlign: 'center',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  homecardvalueSmall: {
    width: 60,
    height: 60,
    borderRadius: 50,
    backgroundColor: '#9BBBBE4D',
    justifyContent: 'center',
    alignContent: 'center',
    borderWidth: 4,
    borderColor: '#9BBBBE',
    textAlign: 'center',
    overflow: 'hidden',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
  homecardNoSmall: {
    color: '#9BBBBE',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    textAlign: 'center',
  },
  homecardvalueActivieSmall: {
    width: 60,
    height: 60,
    borderRadius: 50,
    backgroundColor: '#CED4D8',
    justifyContent: 'center',
    alignContent: 'center',
    borderWidth: 4,
    borderColor: '#495F75',
    textAlign: 'center',
    overflow: 'hidden',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
  homecardNoActSmall: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 12,
    textAlign: 'center',
  },
  datesSelector: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    textAlign: 'center',
  },
  datesSelectorCurrent: {
    color: '#fff',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    textAlign: 'center',
  },
  // overall health
  minView: {
    flexDirection: 'column',
    // alignItems:'center',
    marginTop: 'auto',
    marginBottom: 'auto',
    marginLeft: 12,
  },
  actMinText: {
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    marginTop: 10,
  },
  // profile-switch
  profileList: {
    padding: 30,
  },
  datescroll: {
    borderWidth: 1,
    borderColor: '#CED4D8',
    borderRadius: 10,
    justifyContent: 'center',
    margin: 5,
    backgroundColor: '#CED4D8',
    width: 81,
    height: 97,
    // padding:10
  },
  datescrollCurrent: {
    borderWidth: 1,
    borderColor: '#495F75',
    borderRadius: 10,
    justifyContent: 'center',
    margin: 5,
    backgroundColor: '#495F75',
    width: 81,
    height: 97,
  },
  dflexonly: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 20,
  },
  flexdiet1: {
    flex: 1,
  },
  flexdiet2: {
    flex: 1,
    // width:200
  },
  brownbutton: {
    backgroundColor: '#AE5F5A',
    paddingHorizontal: 20,
    marginHorizontal: 10,
    alignItems: 'center',
    paddingVertical: 5,
    borderRadius: 10,
  },
  conifrmtext: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    fontSize: 17,
    paddingTop: 10,
  },
  comight: {
    flexDirection: 'column',
  },
  comact4: {
    alignItems: 'center',
    overflow: 'hidden',
    flex: 1,
    marginBottom: 30,
  },
  comminner: {
    marginHorizontal: 10,
    flex: 1,
    marginLeft: 'auto',
    marginRight: 'auto',
    alignItems: 'center',
    // borderWidth:1,
    // borderColor:'red',
    // margin:10
  },
  measurementVal: {
    textAlign: 'left',
    // borderWidth:1,
    //   borderColor:'yellow',
    width: '100%',
  },
  maptext: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    fontSize: 18,
    // marginHorizontal:30,
    padding: 20,
  },
  homecardtext5: {
    color: '#436077',
    fontFamily: 'Montserrat-Bold',
    fontSize: 17,
  },
  homecardtext6: {
    color: '#436077',
    fontFamily: 'Montserrat',
    fontSize: 17,
  },
  discimg: {
    width: 200,
    height: 200,
  },

  // priya- frineds-i-met
  friendIMetName: {
    width: 'auto',
    padding: 8,
    borderWidth: 2,
    borderColor: '#CDD4D9',
    borderRadius: 10,
  },
  mainDiv: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    // justifyContent:'space-evenly',
    alignItems: 'flex-start',
  },
  addFriendBtn: {
    marginRight: 0,
    backgroundColor: '#436077',
    height: 50,
    borderRadius: 8,

    // padding:6,
    // borderRadius:3,
    // marginTop:-3
  },
  addFriendBtnSmall: {
    marginRight: 0,
    backgroundColor: '#436077',
    borderRadius: 3,
    padding: 6,
    borderRadius: 3,
    marginTop: -3,
  },
  addtext: {
    fontSize: 15,
    color: '#fff',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
  addtextSmall: {
    fontSize: 14,
    color: '#fff',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
  addFriendBtnPopup: {
    marginRight: 0,
    backgroundColor: '#436077',
    padding: 7,
    borderRadius: 10,
    width: '100%',
  },
  addtextPopup: {
    fontSize: 18,
    // fontSize:17,
    color: '#fff',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 'auto',
    marginBottom: 'auto',
    lineHeight: 24,
  },
  addtextPopupHead: {
    fontSize: 18,
    // fontSize:17,
    color: '#436077',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 'auto',
    marginBottom: 'auto',
    lineHeight: 32,
  },
  imgSliderAct: {
    margin: 12.5,
  },
  addimgplcaeholder: {
    textAlign: 'center',
    marginTop: 'auto',
    marginBottom: 'auto',
    fontFamily: 'Montserrat-Medium',
    fontSize: 13,
    color: '#495F75',
  },
  actIcon: {
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 10,
    alignItems: 'center',
    padding: 20,
    margin: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.41,
    elevation: 23,
  },
  uploadphotomainPop: {
    textAlign: 'center',
  },

  // tinyLogo:{
  //   width:110,
  //   height:110,
  //   backgroundColor:"#fff",
  //   shadowColor: '#000',
  //   shadowOffset: {
  //     width: 0,
  //     height: 1,
  //   },
  //   shadowOpacity: 0.2,
  //   shadowRadius: 2.41,
  //   elevation: 23,
  //   borderWidth:1,
  //   borderColor:'#eee',
  //   borderRadius:10,
  //   alignItems:'center',
  //   padding:10,
  //   margin:10,
  // },
  // dogimage:{
  //   width:100,
  //   height:100,
  // }
  homecardvalueSmallCompare: {
    width: 75,
    height: 75,
    borderRadius: 50,
    backgroundColor: '#9BBBBE4D',
    justifyContent: 'center',
    alignContent: 'center',
    borderWidth: 4,
    borderColor: '#9BBBBE',
    textAlign: 'center',
    overflow: 'hidden',
    marginTop: 'auto',
    marginBottom: 'auto',
  },
  homecardNoSmallCompare: {
    color: '#9BBBBE',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    textAlign: 'center',
  },
  // active-time-tab
  tabmainBar: {
    flex: 1,
    backgroundColor: '#CED4D8',
    borderRadius: 0,
    overflow: 'hidden',
    borderRadius: 3,
  },
  tabSec: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
  },
  // borderBottomColor: active ? "#495F75" : "#CED4D8",
  // borderBottomWidth:4,
  activeTabBar: {
    width: '25%',
    color: '#fff',
    backgroundColor: '#495F75',
    padding: 10,
    borderRadius: 50,
    // borderWidth:2,
    // borderColor:'red',
    fontSize: 22,
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
  },
  InactiveTabBar: {
    width: '25%',
    // borderWidth:2,
    // borderColor:'yellow',
    color: '#495F75',
    backgroundColor: '#CED4D8',
    padding: 10,
    fontSize: 22,
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
  },
  activeTabText: {
    color: '#fff',
    fontSize: 22,
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
  },
  InactiveTabText: {
    color: '#495F75',
    fontSize: 22,
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
  },
  selectswitchBar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    padding: 0,
  },
  switchtextBar: {
    fontSize: 22,
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    // paddingTop:10,
    // width:120,
  },
  newReq: {
    fontSize: 22,
    color: '#495F75',
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: 'Montserrat-Medium',
  },
  brownbtnAddFriend: {
    backgroundColor: '#CE5757',
    width: 80,
    overflow: 'hidden',
    paddingVertical: 5,
    borderRadius: 2,
    paddingHorizontal: 10,
    marginRight: 10,
    marginTop: 10,
    textAlign: 'center',
    alignItems: 'center',
  },
  brownbtntextAdd: {
    fontSize: 16,
    color: '#fff',
    fontFamily: 'Montserrat-Medium',
  },

  addmanuallyFeilds: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#CDD4D9',
    padding: 10,
  },
  friendsBottomIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'space-between',
    marginLeft: 0,
    marginRight: 0,
    marginTop: 10,
    marginBottom: 20,
    paddingBottom: 10,
  },
  newsimg2: {
    width: 50,
    height: 50,
  },
  newReqErr: {
    fontSize: 19,
    lineHeight: 28,
    color: '#495F75',
    textAlign: 'center',
    fontFamily: 'Montserrat-Medium',
  },
  placeholderEditAct: {
    marginHorizontal: 20,
    //paddingLeft:40,
    color: '#000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
  },
  activityImgDis: {
    width: 55,
    height: 55,
  },
  cardsShadow: {
    width: '100%',
    height: 'auto',
    alignItems: 'center',
  },
  cardsShadowInner: {
    width: '90%',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.41,
    elevation: 23,
    borderRadius: 10,
    alignItems: 'center',
    padding: 20,
  },
  recText: {
    color: '#495F75',
    fontFamily: 'Montserrat',
    fontWeight: '500',
    // fontSize: 20,
  },
  mapTimerText: {
    color: '#00000090',
    fontFamily: 'Montserrat',
    fontWeight: '500',
    fontSize: 26,
  },
  stopRec: {
    width: 70,
    height: 70,
    borderRadius: 50,
    backgroundColor: '#CE5757',
    justifyContent: 'center',
    alignContent: 'center',
    borderWidth: 4,
    borderColor: '#CE5757',
    textAlign: 'center',
    overflow: 'hidden',
    marginLeft: 'auto',
    marginRight: 'auto',
    marginBottom: -50,
    // zIndex: 1
  },
  stopRecText: {
    color: '#FFF',
    fontFamily: 'Montserrat-Medium',
    fontSize: 17,
    textAlign: 'center',
  },
  map: {
    height: 210,
    width: '100%',
  },
  // drop-test
  dropdown12: {
    position: 'absolute',
    backgroundColor: '#eee',
    // borderWidth:1,
    // borderColor:'red',
    width: 'auto',
    alignItems: 'center',
    top: -14,
    right: 2,
    shadowColor: '#000000',
    shadowRadius: 4,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.5,
  },
  homval: {
    marginBottom: 10,
  },
  homeinnernew: {
    paddingBottom: 0,
    marginBottom: 0,
  },
  chattime: {
    color: '#000',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    textAlign: 'center',
    opacity: 0.4,
  },
  hrline: {
    borderBottomWidth: 0.2,
    borderColor: 'ccc',
  },
  marbottom15: {
    marginBottom: 15,
    marginTop: 15,
  },
  chatimg: {
    width: 60,
    height: 60,
    borderRadius: 50,
    marginRight: 10,
    borderWidth: 3,
    borderColor: '#fff',
  },
  createaccchat: {
    fontSize: 30,
    // lineHeight:20,
    fontFamily: 'Montserrat-Bold',
    textAlign: 'left',
    color: '#436077',
    paddingTop: 0,
  },
  backbtntext: {
    color: '#92bcbf',
    fontSize: 18,
    fontWeight: '500',
  },
  headerhomesingle: {
    // height: 110,
    // paddingTop:50,
    paddingHorizontal: 15,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: 30,
    ...Platform.select({
      ios: {
        paddingTop: 60,
        // height: 100,
      },
      android: {
        paddingTop: 20,
        height: 80,
      },
    }),
  },
  secext: {
    paddingLeft: 0,
    fontFamily: 'Montserrat-Medium',
  },

  petusername: {
    fontFamily: 'Montserrat-Medium',
    textAlign: 'center',
    marginBottom: 10,
    color: '#CE5757',
  },
  drpdownAct: {
    flex: 1,
    marginLeft: 10,
  },
  inputContainerAct: {
    borderWidth: 1, // Create border
    borderRadius: 8, // Not needed. Just make it look nicer.
    zIndex: 0, // Ensure border has z-index of 0
    paddingLeft: 9,
    // paddingTop:30,
    ...Platform.select({
      ios: {
        paddingTop: 12,
        paddingBottom: 10,
      },
      android: {
        paddingTop: 12,
        paddingBottom: 3,
      },
    }),
    // paddingBottom:3,
    color: '#436077',
    borderColor: '#CDD4D9',
  },

  backinnert: {
    flexDirection: 'row',
  },
  loadingcontainer: {
    flex: 1,
    justifyContent: 'center',
  },
  attach: {
    marginTop: 1,
  },
  toolbar: {
    borderRadius: 20,
    marginHorizontal: 10,
    marginBottom: 10,
    borderTopWidth: 0,
    textAlign: 'center',
  },
  chatsingle: {
    width: 20,
  },
  chatsignlemain: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  findnewbtn: {
    textAlign: 'center',
    // fontWeight: '600',
    fontSize: 20,
    marginTop: 8,
    fontFamily: 'Montserrat-Medium',
  },
  logoutmain: {
    marginTop: 100,
  },
  homval: {
    marginTop: 13,
  },
  homecardmainhealth: {
    paddingBottom: 0,
    marginBottom: 0,
  },

  chatsignlemain: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },

  // Otp

  otpText: {
    color: '#495F75',
    fontFamily: 'Montserrat',
    fontWeight: '500',
    fontSize: 22,
    textAlign: 'center',
    margin: 20,
  },
  otpInput: {
    marginBottom: 10,
    fontFamily: 'Montserrat-Medium',
  },

  homecardmainhealth1: {
    paddingBottom: 30,
  },
  arrowstyle: {
    marginBottom: 70,
  },
  acttype: {
    ...Platform.select({
      ios: {},
      android: {
        paddingTop: 8,
        paddingBottom: 8,
      },
    }),
  },
  requestSentbtn: {
    backgroundColor: '#BE7542',
    width: 80,
    overflow: 'hidden',
    paddingVertical: 5,
    borderRadius: 2,
    paddingHorizontal: 10,
    marginRight: 10,
    marginTop: 10,
    textAlign: 'center',
    alignItems: 'center',
  },
  marhoz25: {
    marginHorizontal: 25,
    flexDirection: 'row',
    gap: 20,
  },
  calendarBackBtn: {
    color: '#B85A57',
    fontFamily: 'Montserrat-Bold',
    fontSize: 25,
  },
  editBtn: {
    flexDirection: 'row',
    marginHorizontal: 50,
  },
  newFrndTitle: {
    textAlign: 'center',
    color: '#B85A57',
    fontFamily: 'Montserrat-Medium',
    fontSize: 20,
  },
  addperbtn: {
    width: 130,
    marginHorizontal: 20,
    paddingHorizontal: 30,
  },
  personalitystyle: {
    flex: 1,
    // borderWidth: 3,
    // borderRadius:20,
    // borderColor:'#436077',
    justifyContent: 'center',
    alignItems: 'center',
  },

  selectedPersonalitystyle: {
    flex: 1,
    borderWidth: 3,
    borderRadius: 20,
    borderColor: '#436077',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bluebtnsmall1: {
    // flexDirection:"row",
    backgroundColor: '#436077',
    width: '50%',
    alignItems: 'center',
    paddingVertical: 15,
    borderRadius: 10,
    marginBottom: 20,
    margin: 10,
    padding: 4,
  },
  Svg_back: {
    backgroundColor: '#436077',
    width: 90,
    padding: 15,
    textAlign: 'center',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  sub_whole: {
    marginTop: 30,
    flex: 1,
    flexDirection: 'row',
  },
  svg_center: {
    marginTop: 20,
    alignSelf: 'center',
  },
  thanks_Iwil: {
    color: '#495F75',
    marginTop: 30,
    fontSize: 20,
    textAlign: 'center',
    fontFamily: 'Montserrat-bold',
  },
  subs_pay: {
    color: '#000',
    marginTop: 30,
    fontSize: 12,
    textAlign: 'center',
    fontFamily: 'Montserrat',
    fontWeight: '100',
    opacity: 0.4,
  },
  tc_privacytext: {
    color: '#CE5757',
    marginTop: 20,
    fontSize: 16,
    textAlign: 'center',
    fontFamily: 'Montserrat',
    fontWeight: '500',
    opacity: 0.4,
    marginRight: 30,
    marginLeft: 30,
  },
  cards_monthly: {
    backgroundColor: '#92BCBF',
    borderRadius: 10,
    margin: 5,
    // alignSelf:'center',
    padding: 5,
    flex: 0.5,
    height: 180,
  },
  cards_Yearly: {
    backgroundColor: '#CE5757',
    borderRadius: 10,
    margin: 5,
    // alignSelf:'center',
    padding: 5,
    flex: 0.5,
  },
  save_per: {
    alignSelf: 'center',
    padding: 10,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#FFFFFF',
    backgroundColor: '#CE5757',
    top: -20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  save_inner: {
    fontSize: 20,
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Montserrat-bold',
  },

  year_fir: {
    fontSize: 25,
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Montserrat-bold',
  },

  year_firs: {
    fontSize: 25,
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Montserrat-bold',
  },

  year_sec: {
    fontSize: 18,
    marginTop: 20,
    marginBottom: 20,
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Montserrat-bold',
  },
  year_tir: {
    fontSize: 12,
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Montserrat-medium',
    opacity: 10,
  },
  tick_sec: {
    flex: 0.5,
    marginTop: 30,
    flexDirection: 'row',
    paddingLeft: 30,
    paddingRight: 30,
  },
  tick_third: {
    flex: 0.5,
    marginTop: 10,
    flexDirection: 'row',
    paddingLeft: 30,
    paddingRight: 30,
  },
  tick_four: {
    flex: 0.5,
    marginTop: 10,
    marginBottom: 10,
    flexDirection: 'row',
    paddingLeft: 30,
    paddingRight: 30,
  },
  innerText: {
    fontWeight: '800',
  },
  text_inner: {
    fontSize: 16,
    paddingLeft: 15,
    color: '#436077',
    fontFamily: 'Montserrat',
    paddingTop: 5,
  },
  cardYearlyOuter: {
    flex: 0.5,
  },
  year_save: {
    paddingBottom: 70,
  },
  timerText: {
    fontSize: 30,
    // marginBottom: 20,
    margin: 10,
  },
  active_per: {
    alignSelf: 'center',
    padding: 5,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#FFFFFF',
    backgroundColor: '#CE5757',
    top: -20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    width: 150,
    height: 30,
    borderColor: '#495F75',
    borderWidth: 3,
  },
  active_inner: {
    fontSize: 12,
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Montserrat-bold',
  },
  active_per_month: {
    alignSelf: 'center',
    padding: 5,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#FFFFFF',
    backgroundColor: '#9BBBBE',
    top: -20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    width: 150,
    height: 30,
    borderColor: '#495F75',
    borderWidth: 3,
  },
  modalinnerText: {
    marginBottom: 5,
    textAlign: 'center',
    color: '#495F75',
    fontFamily: 'Montserrat-Regular',
    fontSize: 14,
    // marginTop: -25,
  },
  buttonSubs: {
    alignItems: 'flex-end',
    padding: 5,
    backgroundColor: '#CE5757',
    borderRadius: 8,
    margin: 5,
  },
  buttonconfirm2: {
    alignItems: 'flex-end',
    padding: 10,
    backgroundColor: '#CE5757',
    borderRadius: 8,
    margin: 10,
  },
  buttonconfirm3: {
    alignItems: 'flex-end',
    padding: 10,
    backgroundColor: '#CE5757',
    borderRadius: 8,
    margin: 10,
  },
  btnText1: {
    color: '#fff',
    fontFamily: 'Montserrat-Regular',
    fontSize: 14,
    textAlign: 'center',
    padding: 5,
  },
  btnText2: {
    color: '#fff',
    fontFamily: 'Montserrat-Regular',
    fontSize: 14,
    textAlign: 'center',
    padding: 2,
  },
  emailmainMediumbtn: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 550,
  },
  emailsheetmain: {
    backgroundColor: '#fff',
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 20,
    height: 800,
  },
  unFriendTtl: {
    textAlign: 'center',
    fontFamily: 'Montserrat-bold',
    fontSize: 18,
    color: '#CE5757',
  },
  receivechatimg: {
    width: 30,
    height: 30,
    borderRadius: 50,
    marginRight: 10,
    borderWidth: 3,
    borderColor: '#fff',
  },
  deleteaccbtn: {
    backgroundColor: '#F2706D',
    width: '90%',
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    margin: 26,
  },
  imageContainer: {
    backgroundColor: '#000000',
    width: '100%',
    height: '100%',
  },
  expandimg: {
    width: '100%',
    height: '100%',
    // marginTop:30,
    // marginBottom:30
  },
  imgcloseBtn: {
    alignSelf: 'flex-end',

    backgroundColor: '#fff',
    borderRadius: 20,
    ...Platform.select({
      ios: {
        margin: 50,
      },
      android: {
        margin: 10,
      },
    }),
  },
  profileContainer: {
    margin: 30,
    alignSelf: 'flex-start',
  },
  activitytextMain: {
    fontSize: 17,
    fontFamily: 'Montserrat-Medium',
    color: '#495F75',
    paddingTop: 10,
    alignSelf: 'flex-start',
  },
  imgSection: {
    // alignSelf: 'flex-start',
    flexDirection: 'row',
    // flex:1,
  },
  imagelist: {
    flexDirection: 'row',
    alignContent: 'space-around',
    paddingLeft: 10,
    borderWidth: 5,
  },
  msgContainer: {
    flex: 1,
    margin: 10,
  },
  commentBox: {
    flexDirection: 'row',
    alignContent: 'center',
  },
  commentInp: {
    borderRadius: 20,
    //   marginHorizontal: 10,
    marginBottom: 10,
    borderTopWidth: 0,
    textAlign: 'center',
    backgroundColor: '#fff',
    width: '90%',
  },
  likesSec: {
    flexDirection: 'row',
    paddingLeft: 10,
    marginBottom: 20,
  },
  likeIcon: {
    alignItems: 'center',
    marginTop: 10,
  },
  likescontainer: {
    marginTop: 20,
    flexDirection: 'row',
    // gap: 10,
    // alignContent: 'flex-end',
  },
  commentTitle: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    color: '#000',
    fontWeight: '800',
    paddingBottom: 10,
  },
  commentText: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
  },
  commentItem: {
    paddingBottom: 10,
    marginBottom: 10,
    flex: 0.5,
    backgroundColor: '#ede9e8',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
  },
  settingsTitle: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    fontWeight: '800',
    padding: 8,
  },
  settingmainText: {
    fontSize: 20,
    fontFamily: 'Montserrat-Medium',
    fontWeight: '600',
    textAlign: 'center',
    margin: 20,
  },
  settingsContainer: {
    margin: 25,
    // backgroundColor: '#ffffff',
    // borderRadius: 20,
    // shadowOpacity: 50,
    // shadowOffset: 100,
    // height: 150,
    // shadowColor: '#000',
    // shadowOffset: {
    //   width: 0,
    //   height: 1,
    // },
    // shadowOpacity: 0.5,
    // shadowRadius: 2.41,
  },
  settingsCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 20,
  },
  settingsCard1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 20,
  },
  weightfillText: {
    fontSize: 18,
    color: '#436077',
  },
  likeComment: {
    marginLeft: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  slider: {
    position: 'absolute',
    width: 230,
    height: 40,
    top: 0,
  },
  weightHeightVal: {
    fontSize: 18,
    marginBottom: 20,
    textAlign: 'center',
  },
  verticalSlider: {
    position: 'absolute',
    width: '90%',
    height: 40,
    transform: [{ rotate: '-90deg' }], // Rotate slider to make it vertical
    left: 110,
  },
  trackerStatusmain: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
  },
  badgecontainer: {
    position: 'absolute',
    borderRadius: 10,
    backgroundColor: '#e30b0b',
    height: 20,
    width: 20,
    marginLeft: 20,
    right: -6,
    top: -12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  badgeText: { padding: 2, color: '#fff', fontSize: 9, fontWeight: 'bold' },
  minimumTrack: {
    position: 'absolute',
    backgroundColor: '#436077',
    height: 10, // Increased thickness for the minimum track
    top: 15, // Adjusted for centering the track
    borderRadius: 50,
  },
  maximumTrack: {
    position: 'absolute',
    backgroundColor: '#d3d3d3',
    height: 5, // Default thickness for the maximum track
    width: 230,
    top: 17.5, // Align with the minimum track
  },
  customTrackContainer: {
    width: '90%',
    height: 40,
    position: 'relative',
  },
  comparetext2: {
    textAlign: 'center',
    paddingTop: 10,
  },
  notificationTitle: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 16,
    paddingHorizontal: 10,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  badgeHightLighter: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#4287f5',
    right: 20,
  },
  notificationText: {
    color: '#495F75',
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
    paddingHorizontal: 10,
  },
  underLine: {
    height: 2, // Thin line
    width: '100%', // Full width of the parent container
    backgroundColor: '#dbd3d3', // Line color
    marginVertical: 20,
    marginBottom: 10,
  },
  notificationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center', // Vertically align the items
  },
  joinBtn: {
    backgroundColor: '#436077',
    height: 50,
    marginBottom: 0,
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        marginBottom: 0.45,
        height: 55,
      },
      android: {
      },
    }),
  },
  joinBtn2: {
    backgroundColor: '#436077',
    height: 50,
    marginBottom: 0,
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
    alignItems: 'center',
    ...Platform.select({
      ios: {
        marginBottom: 0,
        height: 55,
      },
      android: {
      },
    }),
  },
  createBtn1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    ...Platform.select({
      ios: {
        marginVertical: 185,
      },
      android: {
      },
    }),
  }
});
